import { expect, test, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import Papa from 'papaparse'
import { createHash } from 'node:crypto'

async function load(page: Page, csv: string, count: number) {
  await page.goto('/app/')
  await page.locator('#csv-input').setInputFiles({ name: 'review.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: new RegExp(`Scan ${count} contacts`) }).click()
  await expect(page.getByRole('heading', { name: 'Scan Complete' })).toBeVisible()
}
async function download(page: Page, name: string) {
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name, exact: true }).click()
  const file = await pending
  const parsed = Papa.parse<Record<string, string>>(readFileSync((await file.path())!, 'utf8'), { header: true })
  expect(parsed.errors).toEqual([])
  return parsed.data
}
const makeQueue = (groups: number) => 'Email,First Name,Last Name,Phone,Record ID,Note\n' + Array.from({ length: groups }, (_, index) => {
  const id = createHash('sha256').update(String(index)).digest('hex')
  return [`${id}@example.com,${id.slice(0, 10)},${id.slice(10, 20)},123456${index},${index}A,first`,
    `${id}@example.com,${id.slice(0, 10)},${id.slice(10, 20)},,${index}B,second`].join('\n')
}).join('\n')

test('row selection preserves focus and field preferences across queue navigation', async ({ page }) => {
  await load(page, makeQueue(8), 16)
  await expect(page.locator('.group-card')).toHaveCount(5)
  const card = page.locator('.group-card').first()
  const id = await card.getAttribute('data-group-id')
  await card.getByLabel('Show all original fields').check()
  await card.locator('.match-explanation summary').click()
  await card.locator('.source-fields summary').click()
  const radio = card.getByRole('radio').nth(1)
  await radio.focus()
  await radio.press('Space')
  await expect(radio).toBeChecked()
  await expect(radio).toBeFocused()
  await expect(card.locator('.source-fields')).not.toHaveAttribute('open')
  await expect(card.locator('.match-explanation details')).toHaveAttribute('open', '')
  await card.locator('.source-fields summary').click()
  await expect(card.getByLabel('Show all original fields')).toBeChecked()
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(page.locator('.group-card')).toHaveCount(3)
  await page.getByRole('button', { name: 'Previous page', exact: true }).click()
  await expect(card).toHaveAttribute('data-group-id', id!)
  await expect(card.getByLabel('Show all original fields')).toBeChecked()
  await expect(card.getByRole('radio').nth(1)).toBeChecked()
  await page.getByLabel('Group status').selectOption('pending')
  await card.getByRole('button', { name: 'Keep selected row', exact: true }).click()
  await expect(page.getByText('Approved groups (1)')).toBeVisible()
  await expect(page.locator('.group-title').first()).toBeFocused()
  await page.getByLabel('Group status').selectOption('approved')
  await expect(page.locator('.group-card')).toHaveCount(1)
  await expect(card.getByRole('radio').nth(1)).toBeChecked()
  await expect(card.getByLabel('Show all original fields')).toBeChecked()
  await card.getByRole('radio').first().click()
  await expect(page.locator('.group-card')).toHaveCount(0)
  await expect(page.getByLabel('Contact review queue')).toBeFocused()
})

test('exclusion preserves raw rows, requires reselection and records restoring in the audit', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await load(page, 'Email,First Name,Last Name,Phone,Record ID,Note\nsame@example.com,Alex,Lee,1234567890,A,first\nsame@example.com,Alex,Lee,,B,second\nsame@example.com,Alex,Lee,,C,third', 3)
  const card = page.locator('.group-card')
  await card.getByLabel('Show all original fields').check()
  await page.getByRole('button', { name: 'Keep row 2 separate', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Keep selected row', exact: true })).toBeDisabled()
  await expect(page.getByText('Choose a remaining row', { exact: false })).toBeVisible()
  await expect(page.locator('.group-title')).toBeFocused()
  await expect(page.locator('input[type="radio"]:checked')).toHaveCount(0)
  await expect(page.getByLabel('Show all original fields')).toBeChecked()
  await page.getByRole('radio', { name: 'Keep CSV row 3', exact: true }).check()
  await page.getByRole('button', { name: 'Keep selected row', exact: true }).click()
  const audit = await download(page, 'Download audit report')
  expect(audit.map(row => row['Row outcome'])).toEqual(['kept-separate', 'kept-selected', 'removed'])
  expect(audit[0].Decision).toBe('keep-separate')
  expect(audit[2]['Values to review']).toContain('Note: third')
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  await page.getByLabel(/I reviewed every approved group/).check()
  const csv = await download(page, 'Download reviewed CSV')
  expect(csv.map(row => row['Record ID'])).toEqual(['A', 'B'])
  expect(csv.map(row => row.Note)).toEqual(['first', 'second'])
  await page.getByRole('button', { name: 'Return row 2 to group', exact: true }).click()
  await expect(page.getByText('Approved groups (0)')).toBeVisible()
  await page.getByRole('button', { name: 'Keep selected row', exact: true }).click()
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  await expect(page.getByLabel(/I reviewed every approved group/)).not.toBeChecked()
  await page.getByLabel(/I reviewed every approved group/).check()
  await expect(page.getByRole('button', { name: 'Download reviewed CSV', exact: true })).toBeDisabled()
  const restoredAudit = await download(page, 'Download audit report')
  expect(restoredAudit[0]['Review actions']).toContain('Row 2: kept separately')
  expect(restoredAudit[0]['Review actions']).toContain('Row 2: returned to group')
  expect(restoredAudit[0]['Row outcome']).toBe('removed')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
})

test('search and pagination do not narrow the exported data or clear approvals', async ({ page }) => {
  await load(page, makeQueue(8), 16)
  await page.getByRole('button', { name: 'Keep selected row', exact: true }).first().click()
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await page.getByRole('button', { name: 'Keep selected row', exact: true }).first().click()
  await page.getByLabel('Search contacts').fill('no-contact-matches-this')
  await expect(page.locator('.group-card')).toHaveCount(0)
  const audit = await download(page, 'Download audit report')
  expect(audit).toHaveLength(16)
  expect(audit.filter(row => row['Row outcome'] === 'removed')).toHaveLength(2)
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  await page.getByLabel(/I reviewed every approved group/).check()
  const csv = await download(page, 'Download reviewed CSV')
  expect(csv).toHaveLength(14)
  await page.getByRole('button', { name: 'Next awaiting group', exact: true }).click()
  await expect(page.getByLabel('Search contacts')).toHaveValue('')
  await expect(page.getByLabel('Group status')).toHaveValue('pending')
  await expect(page.locator('.group-title').first()).toBeFocused()
})
