import { readFileSync, writeFileSync } from 'node:fs'
const dictionaries = Object.fromEntries(['tr', 'de'].map(language => [language, JSON.parse(readFileSync(new URL('../src/i18n/' + language + '.json', import.meta.url), 'utf8'))]))
const runtime = readFileSync(new URL('./static-display.js', import.meta.url), 'utf8')
writeFileSync(new URL('../public/site-display.js', import.meta.url), '// Generated by scripts/build-display.mjs.\nconst dictionaries = ' + JSON.stringify(dictionaries) + ';\n' + runtime)
