const concept = ['a','b','c','d','e','f'].includes(new URLSearchParams(location.search).get('concept')) ? new URLSearchParams(location.search).get('concept') : 'f';
document.body.dataset.concept = concept;
document.querySelector(`[data-concept="${concept}"]`).setAttribute('aria-current','page');
let theme='light';
try { theme=localStorage.getItem('studio-theme')==='dark'?'dark':'light' } catch {}
document.body.dataset.theme=theme;
let lang='tr', active=0, choices=[0,0,0], decisions=[null,null,null];
const words={
tr:{privacy:'Verileriniz tarayıcıda kalır',open:'Kendi CSV dosyanızı açın',title:'Tekrarlanan kişileri net bir kararla ayırın.',intro:'HubSpot dosyanızdaki olası tekrarları karşılaştırın. Hangi satırın kalacağına siz karar verin.',free:'Ücretsiz. Hesap açmanız gerekmez.',sample:'Örnek dosyayla inceleyin',file:'Örnek kişi dosyası',rows:'6 kişi · 3 inceleme grubu',local:'Dosya yüklenmez',review:'Kayıtları karşılaştırın',reason:'Aynı ad, farklı e-posta. Silmeden önce kontrol edin.',field:'Alan',record:'Kayıt',name:'Ad soyad',email:'E-posta',company:'Şirket',stage:'Yaşam döngüsü',keep:'Bu satırı seç',selected:'Seçilen satır',approve:'Seçilen satırı tut',both:'İkisini de tut',warning:'Seçiminiz diğer satırı yeni CSV’den çıkarır. Alanlar birleştirilmez.',unchanged:'HubSpot kayıtlarınız değişmez.',pending:'Karar bekliyor',approved:'Tek satır tutulacak',separate:'İkisi de tutulacak',undo:'Kararı geri al',queue:'İnceleme kuyruğu',done:'karar verildi',original:'Orijinal dosya korunur',proof:'Her kararın kaydı sizde.',proofbody:'Satırları çıkarmadan önce tüm kaynak alanlarını içeren işlem raporunu indirin. Yeni CSV yalnız onayladığınız değişiklikleri içerir.',limits:'Bu araç HubSpot’a bağlanmaz. Daha küçük bir CSV’yi içe aktarmak CRM kayıtlarını birleştirmez veya silmez.',hint:'Bu demoda yalnız kurgusal verilerle karar akışını deneyebilirsiniz.',next:'Sonraki grup',language:'Dil',explain:'Farkları göster',hide:'Tüm alanları göster',changes:'E-posta ve yaşam döngüsü farklı. Her iki kaydın da korunması gerekebilir.',foot:'Bağımsız CSV inceleme aracı',start:'Dosya → Karşılaştırma → İşlem raporu',label:'HubSpot kişi dosyaları için',count:'Çıktıda kalacak örnek satırlar',plan:'İnceleme özeti'},
en:{privacy:'Your data stays in your browser',open:'Open your own CSV',title:'Make a clear call on duplicate contacts.',intro:'Compare possible duplicates in your HubSpot export. You decide which rows to keep.',free:'Free to use. No account needed.',sample:'Review the sample file',file:'Sample contact file',rows:'6 contacts · 3 review groups',local:'No file upload',review:'Compare the records',reason:'Same name, different email. Check before removing a row.',field:'Field',record:'Record',name:'Full name',email:'Email',company:'Company',stage:'Lifecycle stage',keep:'Select this row',selected:'Selected row',approve:'Keep selected row',both:'Keep both',warning:'Your decision removes the other row from the new CSV. Fields are not combined.',unchanged:'Your HubSpot records stay unchanged.',pending:'Awaiting decision',approved:'One row will be kept',separate:'Both rows will be kept',undo:'Undo decision',queue:'Review queue',done:'decided',original:'Original file preserved',proof:'Keep a record of every decision.',proofbody:'Download the audit with all source fields before removing rows. The new CSV includes only the changes you approve.',limits:'This tool does not connect to HubSpot. Importing a smaller CSV does not merge or delete CRM records.',hint:'This demo lets you try the decision flow with fictional data only.',next:'Next group',language:'Language',explain:'Show differences',hide:'Show all fields',changes:'Email and lifecycle stage differ. Both records may need to be kept.',foot:'Independent CSV review tool',start:'File → Comparison → Audit',label:'For HubSpot contact exports',count:'Sample rows kept in the export',plan:'Review summary'},
de:{privacy:'Ihre Daten bleiben im Browser',open:'Eigene CSV öffnen',title:'Kontaktduplikate mit Klarheit prüfen.',intro:'Vergleichen Sie mögliche Duplikate im HubSpot-Export. Sie entscheiden, welche Zeilen bleiben.',free:'Kostenlos. Ohne Konto.',sample:'Beispieldatei prüfen',file:'Beispiel-Kontaktdatei',rows:'6 Kontakte · 3 Prüfgruppen',local:'Kein Datei-Upload',review:'Datensätze vergleichen',reason:'Gleicher Name, andere E-Mail. Vor dem Entfernen prüfen.',field:'Feld',record:'Datensatz',name:'Vollständiger Name',email:'E-Mail',company:'Unternehmen',stage:'Lifecycle-Phase',keep:'Diese Zeile wählen',selected:'Ausgewählte Zeile',approve:'Ausgewählte Zeile behalten',both:'Beide behalten',warning:'Ihre Entscheidung entfernt die andere Zeile aus der neuen CSV. Felder werden nicht kombiniert.',unchanged:'Ihre HubSpot-Datensätze bleiben unverändert.',pending:'Entscheidung ausstehend',approved:'Eine Zeile bleibt',separate:'Beide Zeilen bleiben',undo:'Entscheidung zurücknehmen',queue:'Prüfwarteschlange',done:'entschieden',original:'Originaldatei bleibt erhalten',proof:'Jede Entscheidung dokumentieren.',proofbody:'Laden Sie vor dem Entfernen den Prüfbericht mit allen Quellfeldern herunter. Die neue CSV enthält nur freigegebene Änderungen.',limits:'Dieses Werkzeug verbindet sich nicht mit HubSpot. Der Import einer kleineren CSV führt CRM-Datensätze nicht zusammen und löscht sie nicht.',hint:'Diese Demo zeigt den Entscheidungsablauf ausschließlich mit fiktiven Daten.',next:'Nächste Gruppe',language:'Sprache',explain:'Unterschiede anzeigen',hide:'Alle Felder anzeigen',changes:'E-Mail und Lifecycle-Phase unterscheiden sich. Möglicherweise müssen beide Datensätze bleiben.',foot:'Unabhängiges CSV-Prüfwerkzeug',start:'Datei → Vergleich → Prüfbericht',label:'Für HubSpot-Kontaktexporte',count:'Verbleibende Beispielzeilen',plan:'Prüfübersicht'}};
const contacts=[['Alex Morgan','alex@northstar.example','a.morgan@northstar.example','Northstar'],['Sam Taylor','sam@studio.example','s.taylor@studio.example','Studio Works'],['Robin Lee','robin@fieldwork.example','r.lee@fieldwork.example','Fieldwork']];
if (['d','e','f'].includes(concept)) {
  words.tr.title='Kişi tekrarlarını gözden geçirin.';
  words.en.title='A closer look at duplicate contacts.';
  words.de.title='Kontaktduplikate im Detail prüfen.';
  words.tr.intro='Kayıtları yan yana karşılaştırın. Tutulacak satırları seçin. Orijinal dosyanız değişmesin.';
  words.en.intro='Compare records side by side. Choose the rows to keep. Preserve your original file.';
  words.de.intro='Datensätze nebeneinander vergleichen. Zeilen zum Behalten auswählen. Originaldatei bewahren.';
}
Object.assign(words.tr,{appearance:'Görünüm',light:'Açık',dark:'Koyu'});
Object.assign(words.en,{appearance:'Appearance',light:'Light',dark:'Dark'});
Object.assign(words.de,{appearance:'Darstellung',light:'Hell',dark:'Dunkel'});
let onlyDiff=false; const w=k=>words[lang][k];
function render(){document.documentElement.lang=lang;const person=contacts[active], decided=decisions.filter(Boolean).length, kept=6-decisions.filter(d=>d==='one').length;const row=(key,v1,v2,diff=false)=>`<div class="data-row ${diff?'different':''}" ${onlyDiff&&!diff?'hidden':''}><span>${w(key)}</span><strong>${v1}</strong><strong>${v2}</strong></div>`;
const queue=`<aside class="queue"><div class="queue-title">${w('queue')}<span>${decided}/3</span></div>${contacts.map((p,i)=>`<button class="queue-item ${active===i?'active':''}" data-group="${i}"><span class="avatar">${p[0].split(' ').map(n=>n[0]).join('')}</span><span><b>${p[0]}</b><small>${decisions[i]?w(decisions[i]==='one'?'approved':'separate'):w('pending')}</small></span><span class="queue-mark">${decisions[i]?'✓':'›'}</span></button>`).join('')}<div class="queue-bottom"><span>${w('plan')}</span><strong>${kept} / 6</strong><small>${w('count')}</small></div></aside>`;
const sheet=`<section class="sheet" id="review" aria-label="${w('review')}"><div class="sheet-top"><span class="file-glyph">≡</span><div><b>contacts_sample.csv</b><small>${w('rows')}</small></div><span class="local-badge">◉ ${w('local')}</span></div><div class="sheet-heading"><div><span class="group-index">${active+1} / 3</span><h2>${w('review')}</h2><p>${w('reason')}</p></div><button class="filter" id="diff" aria-pressed="${onlyDiff}">${w(onlyDiff?'hide':'explain')}</button></div><div class="comparison"><div class="data-row column-head"><span>${w('field')}</span>${[0,1].map(i=>`<label class="record-choice ${choices[active]===i?'chosen':''}"><input type="radio" name="row" value="${i}" ${choices[active]===i?'checked':''}><span>${w('record')} ${i?'B':'A'}<small>${w(choices[active]===i?'selected':'keep')}</small></span></label>`).join('')}</div>${row('name',person[0],person[0])}${row('email',person[1],person[2],true)}${row('company',person[3],person[3])}${row('stage','Customer','Lead',true)}</div><div class="decision"><div class="decision-note"><span class="note-icon">↳</span><p>${decisions[active]?w(decisions[active]==='one'?'approved':'separate'):w('warning')}</p></div><div class="decision-buttons">${decisions[active]?`<button id="undo" class="secondary">${w('undo')}</button><button id="next" class="primary">${w('next')} →</button>`:`<button id="both" class="secondary">${w('both')}</button><button id="approve" class="primary">${w('approve')} →</button>`}</div></div><p class="demo-note">${w('hint')}</p></section>`;
const intro=`<section class="intro"><p class="context">${w('label')}</p><h1>${w('title')}</h1><p class="lede">${w('intro')}</p><div class="intro-actions"><a class="primary" href="http://127.0.0.1:4175/app/">${w('open')} ↗</a><a class="sample" href="#review">${w('sample')} ↓</a></div><p class="free">${w('free')}</p><div class="file-card"><span class="file-symbol">CSV</span><div><b>${w('file')}</b><small>${w('rows')}</small></div><span>↗</span></div><p class="file-caption">${w('unchanged')}</p></section>`;
document.getElementById('root').innerHTML=`<header><a class="brand" href="?concept=${concept}"><span class="brand-mark">d<span>↗</span></span>DedupeSafe</a><div class="header-right"><span class="privacy">${w('privacy')}</span><label class="lang"><span class="sr">${w('language')}</span><select aria-label="${w('language')}" id="lang">${['tr','en','de'].map(l=>`<option value="${l}" ${lang===l?'selected':''}>${{tr:'Türkçe',en:'English',de:'Deutsch'}[l]}</option>`).join('')}</select></label><label class="lang"><span class="sr">${w('appearance')}</span><select id="theme" aria-label="${w('appearance')}">${['light','dark'].map(v=>`<option value="${v}" ${theme===v?'selected':''}>${w(v)}</option>`).join('')}</select></label></div></header><main><div class="layout">${intro}<div class="workbench">${queue}${sheet}</div></div><section class="bottom"><div><span class="audit-icon">≡</span><h2>${w('proof')}</h2></div><p>${w('proofbody')}</p><p class="limits">${w('limits')}</p></section></main><footer><b>DedupeSafe</b><span>${w('foot')}</span><span>${w('original')} ↗</span></footer><p class="sr" role="status">${decided}/3 ${w('done')}. ${kept}/6</p>`;
document.getElementById('theme').onchange=e=>{theme=e.target.value;document.body.dataset.theme=theme;try{localStorage.setItem('studio-theme',theme)}catch{}};document.getElementById('lang').onchange=e=>{lang=e.target.value;render()};document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{active=Number(b.dataset.group);render()});document.querySelectorAll('[name=row]').forEach(r=>r.onchange=()=>{choices[active]=Number(r.value);decisions[active]=null;render()});document.getElementById('diff').onclick=()=>{onlyDiff=!onlyDiff;render()};for(const [id,value]of [['approve','one'],['both','both'],['undo',null]]){const el=document.getElementById(id);if(el)el.onclick=()=>{decisions[active]=value;render();document.querySelector('#undo,#approve')?.focus()}}const next=document.getElementById('next');if(next)next.onclick=()=>{active=(active+1)%3;render()};}
render();
